In [15]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [16]:
interpreter = tf.lite.Interpreter(model_path="lite-model_movenet_singlepose_thunder_3.tflite")
interpreter.allocate_tensors()

In [17]:
lowerjoints_list = [13,14,15,16]

In [18]:
for i in joints_coordinates:
    y, x, conf = i
    print(int(y), int(x), kp_conf)

NameError: name 'joints_coordinates' is not defined

In [19]:
def locating_joints(frame, keypoints, confidence_threshold):
    #y, x, c = frame.shape
    for i in lowerjoints_list:
        y, x, conf = joints_coordinates[i]
        if conf > confidence_threshold:
            cv2.circle(frame, (int(x), int(y)), 4, (0,255,0), -1)

In [20]:
def knee_distance(frame,point):
   # y, x, c = frame.shape
    y1,x1 ,_ = joints_coordinates[13]
    y2, x2,_ = joints_coordinates[14]
    import math
    temp = (x2-x1)**2+(y2-y1)**2
    distance = math.sqrt(temp)
    cv2.putText(frame,"Distance:" + str(distance), (0,50), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
    
    

In [21]:
def left_slope(frame,point):
  import math
  #y, x, c = frame.shape
  y1,x1 ,_ = joints_coordinates[15]
  y2, x2,_ = joints_coordinates[13]
  m = (y2-y1)/(x2-x1)
  cv2.putText(frame,"left slope:" + str(m), (50,100), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  

In [22]:
def ankle_distance(frame,point):
    #y, x, c = frame.shape
    y1,x1 ,_ = joints_coordinates[15]
    y2, x2,_ = joints_coordinates[16]
    import math
    temp = (x2-x1)**2+(y2-y1)**2
    distance = math.sqrt(temp)
    cv2.putText(frame," Ank:" + str(distance), (150,200), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
    
    

In [23]:
def right_slope(frame,point):
  import math
  #y, x, c = frame.shape
  y1,x1 ,_ = joints_coordinates[16]
  y2,x2,_ = joints_coordinates[14]
  m2 = (y2-y1)/(x2-x1)
  cv2.putText(frame,"Right slope:" + str(m2), (100,150), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  

In [24]:
EDGES = {
    (13, 15): 'm',
    #(12, 14): 'c',
    (14, 16): 'c',
    (13, 14): 'c',
    (16,15) : 'm'
}

In [25]:
def join_joints(frame, keypoints, edges, confidence_threshold):
    #y, x, c = frame.shape
    print(keypoints.shape)

    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = joints_coordinates[p1]
        y2, x2, c2 = joints_coordinates[p2]
        
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
           cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)


In [26]:
def insoles(frame): 
  y1,x1 ,_ = joints_coordinates[13]
  y2,x2,_ = joints_coordinates[14] 
  y3,x3 ,_ = joints_coordinates[15]
  y4,x4,_ = joints_coordinates[16]
  import math 
  dis = (x2-x1)**2+(y2-y1)**2
  ankle_dis = (x4-x3)**2+(y4-y3)**2
  right_m= (y4-y2)/(x4-x2)
  left_m = (y3-y1)/(x3-x1)
  print("knee:", dis)
  print("ankle:", ankle_dis)
  print("left",left_m)
  print("Right",right_m)
#8739.635093408378
  
  #cv2.putText(frame,"insole", (100,250), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  ankle = (x4-x3)**2+(y4-y3)**2
  #dis below 88 and ankle below 88, dis >80 and ankle > 80
  if (dis <= 7195.855191894665 and dis > 5608.360385571377 and ankle_dis <= 7195.855191894665 and ankle_dis > 5608.855051436771) or (dis < 7195.855191894665 and dis > 6495.855191894665 and ankle_dis >= 7195.855191894665 and ankle_dis <= 7795.855191894665 ):
     print("running loop 1")
     cv2.putText(frame,"Medium arch height insole", (100,250), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  elif (dis <= 5608.855051436771 and ankle_dis <= 5608.855051436771) or (dis < 5608.855051436771 and ankle_dis > 5608.855051436771 and ankle_dis <= 5908.855051436771):
     #or (dis > 5608.855051436771 and ankle_dis < 7195.855191894665)
     print("running")
     cv2.putText(frame,"Low arch height insole", (100,250), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  elif (dis >= 7195.855191894665 and ankle_dis >= 7195.855191894665):
     cv2.putText(frame,"High arch height insole", (100,250), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
  else:
     cv2.putText(frame,"Other medical condition", (100,250), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
     pass
            
       
        
        

        
    
    

In [27]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0),256,256)
    input_image = tf.cast(img, dtype=tf.float32)
    
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print(output_details)
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print("hello boy")
    print(keypoints_with_scores)                
    y, x, c = frame.shape
    print("gurs")
    print(np.multiply(keypoints_with_scores, [y,x,1]))
    print("Kaur")
    joints_coordinates = np.squeeze(np.multiply(keypoints_with_scores, [y,x,1]))
    print(joints_coordinates)
    
    # Rendering
    locating_joints(frame, keypoints_with_scores, 0.4) 
    join_joints(frame, keypoints_with_scores, EDGES, 0.4)
    knee_distance(frame,keypoints_with_scores)
    ankle_distance(frame,keypoints_with_scores)
    left_slope(frame,keypoints_with_scores)
    right_slope(frame,keypoints_with_scores)
    insoles(frame)
    cv2.imshow('MoveNet Lightning', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[{'name': 'StatefulPartitionedCall:0', 'index': 312, 'shape': array([ 1,  1, 17,  3]), 'shape_signature': array([ 1,  1, 17,  3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
hello boy
[[[[5.4431874e-01 5.3309339e-01 5.0347531e-01]
   [4.8382398e-01 5.8570063e-01 7.2542459e-01]
   [4.8757052e-01 4.7297329e-01 7.4130189e-01]
   [5.0666058e-01 6.4649695e-01 7.4103630e-01]
   [5.0738752e-01 4.2484859e-01 7.2193199e-01]
   [7.6091635e-01 8.0641782e-01 7.3911953e-01]
   [7.5717390e-01 2.8261617e-01 7.3186982e-01]
   [8.6270750e-01 9.0344346e-01 4.9082339e-03]
   [8.3707219e-01 2.5014660e-01 3.2854676e-03]
   [7.8727812e-01 7.8479230e-01 9.0950429e-03]
   [7.7802598e-01 3.3844194e-01 2.3090661e-02]
   [1.0024698e+00 7.6764923e-01 8.2710385e-04]
   [8.4840977e-01 2.6675233e-01 1.2844205e-02]
   [7.7835453e-01 8.1325048e-0

In [28]:
cap.release()
cv2.destroyAllWindows()